//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 11:07:26 AM BST 
//


package uk.fstr.darwingateway.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.fstr.darwingateway.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PPConnect_QNAME = new QName("http://thalesgroup.com/RTTI/PushPortStatus/root_1", "PPConnect");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.fstr.darwingateway.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pport }
     * 
     */
    public Pport createPport() {
        return new Pport();
    }

    /**
     * Create an instance of {@link StationMessage }
     * 
     */
    public StationMessage createStationMessage() {
        return new StationMessage();
    }

    /**
     * Create an instance of {@link TrainOrderItem }
     * 
     */
    public TrainOrderItem createTrainOrderItem() {
        return new TrainOrderItem();
    }

    /**
     * Create an instance of {@link Pport.TimeTableId }
     * 
     */
    public Pport.TimeTableId createPportTimeTableId() {
        return new Pport.TimeTableId();
    }

    /**
     * Create an instance of {@link Pport.GetSnapshotReq }
     * 
     */
    public Pport.GetSnapshotReq createPportGetSnapshotReq() {
        return new Pport.GetSnapshotReq();
    }

    /**
     * Create an instance of {@link Pport.GetFullSnapshotReq }
     * 
     */
    public Pport.GetFullSnapshotReq createPportGetFullSnapshotReq() {
        return new Pport.GetFullSnapshotReq();
    }

    /**
     * Create an instance of {@link Pport.FailureResp }
     * 
     */
    public Pport.FailureResp createPportFailureResp() {
        return new Pport.FailureResp();
    }

    /**
     * Create an instance of {@link Pport.UR }
     * 
     */
    public Pport.UR createPportUR() {
        return new Pport.UR();
    }

    /**
     * Create an instance of {@link DataResponse }
     * 
     */
    public DataResponse createDataResponse() {
        return new DataResponse();
    }

    /**
     * Create an instance of {@link PPStatus }
     * 
     */
    public PPStatus createPPStatus() {
        return new PPStatus();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link PPReqVersion }
     * 
     */
    public PPReqVersion createPPReqVersion() {
        return new PPReqVersion();
    }

    /**
     * Create an instance of {@link DisruptionReasonType }
     * 
     */
    public DisruptionReasonType createDisruptionReasonType() {
        return new DisruptionReasonType();
    }

    /**
     * Create an instance of {@link PP }
     * 
     */
    public PP createPP() {
        return new PP();
    }

    /**
     * Create an instance of {@link DT }
     * 
     */
    public DT createDT() {
        return new DT();
    }

    /**
     * Create an instance of {@link AssocService }
     * 
     */
    public AssocService createAssocService() {
        return new AssocService();
    }

    /**
     * Create an instance of {@link OPOR }
     * 
     */
    public OPOR createOPOR() {
        return new OPOR();
    }

    /**
     * Create an instance of {@link DeactivatedSchedule }
     * 
     */
    public DeactivatedSchedule createDeactivatedSchedule() {
        return new DeactivatedSchedule();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link OR }
     * 
     */
    public OR createOR() {
        return new OR();
    }

    /**
     * Create an instance of {@link OPDT }
     * 
     */
    public OPDT createOPDT() {
        return new OPDT();
    }

    /**
     * Create an instance of {@link IP }
     * 
     */
    public IP createIP() {
        return new IP();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link OPIP }
     * 
     */
    public OPIP createOPIP() {
        return new OPIP();
    }

    /**
     * Create an instance of {@link PlatformData }
     * 
     */
    public PlatformData createPlatformData() {
        return new PlatformData();
    }

    /**
     * Create an instance of {@link TSLocation }
     * 
     */
    public TSLocation createTSLocation() {
        return new TSLocation();
    }

    /**
     * Create an instance of {@link TSTimeData }
     * 
     */
    public TSTimeData createTSTimeData() {
        return new TSTimeData();
    }

    /**
     * Create an instance of {@link TS }
     * 
     */
    public TS createTS() {
        return new TS();
    }

    /**
     * Create an instance of {@link TrainOrder }
     * 
     */
    public TrainOrder createTrainOrder() {
        return new TrainOrder();
    }

    /**
     * Create an instance of {@link TrainOrderData }
     * 
     */
    public TrainOrderData createTrainOrderData() {
        return new TrainOrderData();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link A }
     * 
     */
    public A createA() {
        return new A();
    }

    /**
     * Create an instance of {@link AlertService }
     * 
     */
    public AlertService createAlertService() {
        return new AlertService();
    }

    /**
     * Create an instance of {@link TrainAlert }
     * 
     */
    public TrainAlert createTrainAlert() {
        return new TrainAlert();
    }

    /**
     * Create an instance of {@link AlertServices }
     * 
     */
    public AlertServices createAlertServices() {
        return new AlertServices();
    }

    /**
     * Create an instance of {@link TrackingID }
     * 
     */
    public TrackingID createTrackingID() {
        return new TrackingID();
    }

    /**
     * Create an instance of {@link FullTDBerthID }
     * 
     */
    public FullTDBerthID createFullTDBerthID() {
        return new FullTDBerthID();
    }

    /**
     * Create an instance of {@link RTTIAlarmData }
     * 
     */
    public RTTIAlarmData createRTTIAlarmData() {
        return new RTTIAlarmData();
    }

    /**
     * Create an instance of {@link RTTIAlarm }
     * 
     */
    public RTTIAlarm createRTTIAlarm() {
        return new RTTIAlarm();
    }

    /**
     * Create an instance of {@link StationMessage.Station }
     * 
     */
    public StationMessage.Station createStationMessageStation() {
        return new StationMessage.Station();
    }

    /**
     * Create an instance of {@link StationMessage.Msg }
     * 
     */
    public StationMessage.Msg createStationMessageMsg() {
        return new StationMessage.Msg();
    }

    /**
     * Create an instance of {@link TrainOrderItem.Rid }
     * 
     */
    public TrainOrderItem.Rid createTrainOrderItemRid() {
        return new TrainOrderItem.Rid();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://thalesgroup.com/RTTI/PushPortStatus/root_1", name = "PPConnect")
    public JAXBElement<Object> createPPConnect(Object value) {
        return new JAXBElement<Object>(_PPConnect_QNAME, Object.class, null, value);
    }

}
