//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 11:07:26 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.thalesgroup.com/rtti/PushPort/Schedules/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.fstr.darwingateway.bindings;
